### ISSUE TITLE
$tpl->cache, is there something similar is RainTPL 3?

### ISSUE THREAD

**Issue by InteliClic** [rainphp/raintpl3#168]
I have some code that I have been using with RainTPL 2, however I needed the DrawString function so I updated to RainTPL 3 however now I cannot seem to find a solution for this:

        if ($cache = $tpl->cache('getPage', $expire_time = 10000, $cache_id)) {
            // We have data in cache so lets use it
            $funnel_data = json_decode(base64_decode($cache));
        } else {
            $test_data = $client->getPage($url);
            $json = base64_encode(json_encode($test_data));
            // Set the variable defined in the template
            $tpl->assign('json_data', $json);
            // This draws the data in the cache file and we return the output instead of echo it so that we can continue with that logic.
            $tpl->draw('getPage', true);
        }

Is there anyway to see if the cache exists and load it from there? The documentation for checking the cache doesn't seem to be available. Also none of the examples seem to show this. Any help would be extremely appreciated.

**Comment by rainphp** [comment]
Raintpl 3 doesn't implement any cache, because we think that is not the template engine responsibility to provide one. You want to use an external cache library to solve your problem.

**Comment by InteliClic** [comment]
Ok fair enough. which cache library do you recommend?

**Comment by rainphp** [comment]
Depends by your app. Custom for small app, cache server for high scale.
