### ISSUE TITLE
Infinite loop in reducePath

### ISSUE THREAD

**Issue by xPaw** [rainphp/raintpl3#171]
When there's a path like `Forum\../footer`, it will keep just looping in while() without replacing anything.

**Comment by webnull** [comment]
Where are you have that path? In include tag or in PHP code?

**Comment by xPaw** [comment]
Template

**Comment by webnull** [comment]
So, it's placed inside a {include} tag, right?

You have for example:

```
{include="Forum\../footer"}
```

That's correct?

**Comment by xPaw** [comment]
It's ../footer inside a forum folder.

**Comment by webnull** [comment]
Hmm... with the "\" the path is not valid. Anyway it shouldn't cause infinite loop.

**Comment by xPaw** [comment]
Hm, looks like e8ece72c505079314c8cdcc219decadfe3c7c359 changes directory separator to always be `/`, and bc6fd8a70a8f6ae4b6f100ec3de2579440ea83ed actually fixes the issue.

I should probably update RainTPL in my project.
