### ISSUE TITLE
RainTPL next generation

### ISSUE THREAD

**Issue by webnull** [rainphp/raintpl3#172]
Hello,

I'm proud to announce that I'm working on a RainTPL refactoring that includes rewrited parser and templating engine.

What's new?
- First compiler performance comparsion results showed about **90 times faster compilation** times after moving from regular expressions to pointer-based parsing
- Compatibility with RainTPL3 and partialy with *Smarty*
- Better syntax handling in parsed tags - now there is less propability that for example a space would break a code
- New tags: **{capture}, {block}, {print}, {mark}, {goto}, {foreach}, {extends}**
- Object oriented/functional tag parsing (a callable function with proper interface could be used as a parser)
- RainTPL4 templating engine with corrected mess with configuration variables and static methods, global instances
- New Unit tests, it's not covering all the code but there are more tests than in original raintpl3 repository, also there are some tests made for issues reported on github
- **More understandable parser errors that points to a concrete template file, line and even offset**

What will be coming:
- RainTPL4 templating engine will have a faster plugin system, not complicated so much as the current is
- A special RainTPL3 compatibility layer for plugins, tags and config
- Real sandboxing using PHP parsing class (available as a plugin)
- Configuration refactoring in parser

The link for a fork is here:
https://github.com/Panthera-Framework/raintpl4

After I pre-finish work on current tasks I suggest merging the fork or creating a separate a project in a RainTPL organization on github (if there isn't any then create it?) or moving to a new repository in current organization (Panthera Framework).

Code example:
```
<!-- RainTPL/PHP-like syntax -->
{foreach from="$array" as $key => $value}
{$key} - {$value}
{/foreach}

<!-- Smarty-like syntax -->
{foreach from="$array" item="i" key="k"}
{$k} - {$i}
{/foreach}

{if 5 > 4}
Yes, that's correct.
{else}
Nope.
{/if}

{"test"|substr:0,2} {* will output "te" *}
```

What do you think?
Could you make some tests?
Any suggestions?
Performance and/or code analysis?

**Comment by rainphp** [comment]
Damien that's great to hear. Please include me in the reviews and let me
know how can I help you.

Thanks.

**Comment by webnull** [comment]
At first I will create a complete list of tasks and describe a direction in which way I would like to go with this project.

Currently I will try at first to make a new plugin system which will be more flexible and very lightweight.
After that we will need a completly compatibility layer with RainTPL3 plugins system, and with RainTPL3 tags.

The parser should be almost 99,9% compatible with RainTPL3 as I'm running templates from Panthera Framework project without any problems on refactored templating engine. Also I tested example-all.php manual test and it's working fully.

The problem I noticed in RainTPL3 was the configuration in 3 places and Tpl::configure() function. This was awful, it's complicating creation of multiple RainTPL instances.

Multiple RainTPL3 instances would be used for example to compile single strings on a page eg. when user submits a form, or to process massively some templates etc.

**Comment by webnull** [comment]
So, I would like to finish some parts of RainTPL4 by myself and then invite you all to test all of the functionality, create test cases, test with your projects, fix compatibility issues. Next step - ideas, additional plugins.

**Comment by sitthykun** [comment]
I support you and I am waiting

**Comment by xPaw** [comment]
@webnull I've tried using your fork, and there are 2 blocking issue I've ran into so far:
https://github.com/Panthera-Framework/raintpl3/commit/2498153742407c58da2d0e59d4ed2f473302420f#commitcomment-10677394
https://github.com/Panthera-Framework/raintpl3/commit/25be1b4c7695e213530155482978c487b9d00980#commitcomment-10677407

**Comment by webnull** [comment]
Regarding first issue:
I couldn't check exactly the same testcase, but I noticed that there is something wrong and released a fix.
Please check that fix.

The second issue will be fixed soon. Propably tommorow.

**Comment by webnull** [comment]
As RainTPL4 as fork repository does not have "issues" module avaliable I will update this comment with my todos.

So, the TODO is:
- Fix array variable counter in variables (Parser::varReplace())
- Create a simpler possibility to define own tags
- Support for str_replace (it's problematic due to it's last argument), it could be added as separate modificator name "replace"
- Create a class that will contain all helper functions to use in code (modificators)
- Add some helper functions eg. limitLength (will limit string's length and insert by default eg. "..." at the end - optional argument will be used to change "..." to something else)

**Comment by webnull** [comment]
Performance tests:

Compile once (1x compile + 1000x render):
- RainTPL3: 0.32152199745178s
- RainTPL4: 0.28820991516113s (without sandboxing)
- RainTPL4: 0.30156993865967s (with pseudoSandboxing plugin)

Compile (1000x compile + 1000x render):
- RainTPL3: 4.5723900794983s
- RainTPL4: 6.4950971603394s (without sandboxing)
- RainTPL4: 25.760782003403s (with pseudoSandboxing plugin)

Compile once (1x compile + 1x render):
- RainTPL3: 0.0083250999450684s
- RainTPL4: 0.0103831291198730s (without sandboxing)
- RainTPL4: 0.0366430282592770s (with sandboxing)

Run from cache (0x compile + 1x render):
- RainTPL3: 0.0028510093688965s
- RainTPL4: 0.0028979778289795s

**Comment by rainphp** [comment]
Nice.

**Comment by webnull** [comment]
As we can notice there is no much difference between RainTPL3 and RainTPL4, the biggest difference is in count of functions - RainTPL4 implements more tags and functions than RainTPL3, also featuring a PHP-Parser based sandbox (which is a lot safer than blacklist).

**Comment by webnull** [comment]
Idea: Debugging features

1. In debugging mode we could check where in project code the variable was assigned (PHP stack tracing)
2. Also the place in code where the draw() was called

**Comment by webnull** [comment]
Idea:
Syntax {if "test" in $array} or {if /"test" in $string/} or {if |"test" in $string|} expresions to replace: is_array($array) && in_array("test", $array)

**Comment by webnull** [comment]
Idea:
Plugin support that will compile source code to binary using bcompiler (http://php.net/manual/en/intro.bcompiler.php) - could speed up performance by even 30%

**Comment by xPaw** [comment]
Wouldn't using apc give a nice performance boost too?

**Comment by webnull** [comment]
I don't know, propably. I already thought about that but I would also try bcompiler. It's just an idea. I'm looking for some ideas that would speed up RainTPL to be more faster than Smarty and other templating engines.

**Comment by webnull** [comment]
I converted RainTPL4 from fork to repository to not spam here with 4th version issues.

**Comment by rainphp** [comment]
I preferred it as a fork, but that's fine :)

**Comment by sitthykun** [comment]
Hi, I am sorry but recently I don't any update. 
I am back to PHP project. 
I am applying it for new project.
I am working with PHP 7 project.
If you can you should create a Google Group or forum. So, we can discuss.
