### ISSUE TITLE
Google group for support?

### ISSUE THREAD

**Issue by MB34** [rainphp/raintpl3#173]
On your website, you state that "All the conversation and questions will be done on the RainTPL Google Group". The link goes to: http://groups.google.com/group

That is a bad URL. Can you update that URL? The only one I see when searching for Rain.Tpl is the raincms group: https://groups.google.com/forum/#!forum/raincms

Very short of any questions/answers there.

**Comment by webnull** [comment]
The main website and Google Group requires a update...

**Comment by rainphp** [comment]
I'm going to fix the link thanks.

Now the website is in github page so you can make a pull request for any
changes
https://github.com/rainphp/raintpl/tree/gh-pages

**Comment by rainphp** [comment]
Fixed!
