### ISSUE TITLE
Idea: Easier Ruby/Python-like substr

### ISSUE THREAD

**Issue by webnull** [rainphp/raintpl3#174]
Hello, 

In Ruby and Python there is a possibility to use an array modifier to cut off a string.

Example from Ruby:
```
testVariable[0..5]
```

Example from Python:
```
testVariable[0:5]
# or
testVariable[:5]
```

What do you think about moving it to RainTPL parser? I mean to RainTPL4 now.

**Comment by rainphp** [comment]
That'd be great. Python array modifier is a great feature missing to PHP.

**Comment by xPaw** [comment]
I'm not entirely sure that this would be helpful in templates. This is a pretty much shorter substr syntax.

**Comment by rainphp** [comment]
Pavel made a good point, is probably not worth it to implement.

**Comment by webnull** [comment]
From my experience at work I know that template writers are not familiar with PHP itself. Template syntax should be easy for them, not for programmers only.

**Comment by webnull** [comment]
Also let me decide if it will be worth implementing in RainTPL4 as here it shouldnt be difficult enough.

**Comment by xPaw** [comment]
When was the last time you needed to display a partial string in a template? I just think it's just unnecessary bloat.

**Comment by rainphp** [comment]
This is easier to implement than to discuss, so Damien feel free to
implement this into the alpha version, you can always remove the feature
while moving into the final version.
