### ISSUE TITLE
Is RainTPL dead?

### ISSUE THREAD

**Issue by Abhinav1217** [rainphp/raintpl3#177]
I have loved using RainTPL for its simplicity. I have been using it for over 3 years now. 
But for long time, you have not resolved any bugs, or merged any PR. Nor is there any future plans from you.  I had recommended this to a friend like always but this time i was pointed out to me about inactivity on repo and the website having lots of broken links. So brings my question.

Is RainTPL project dead, or just really really slow on activity?

**Comment by webnull** [comment]
There is a fork that is a little bit faster on activity, you could try:
https://github.com/Panthera-Framework/raintpl4

**Comment by rainphp** [comment]
Hi Abhinav, thanks for asking. There are no plans for future expansion for
now, you can either use RainTPL 2.7 which at this point is stable, or
RainTPL3 also stable (aside a few open bugs), or also try Damian fork into
RainTPL 4.

You're also invited and welcome to contribute to fix the bugs and improve
the code!

Thanks,
Federico

**Comment by Abhinav1217** [comment]
I will try RainTPL 4.  Personally I am very satisfied with RainTPL3. It was only after someone pointed it to me, I noticed pending bugs and pull requests.  Maybe sometimes, I will try to fix some bugs and send you pull requests. Help you maintain it. 

I really liked idea of Raintpl4 fo include preprocessors. Hope it really have  faster performance.

**Comment by Abhinav1217** [comment]
BTW, I really think you should atleast merge some pull requests. The one I am using in my projects contains code from 3 of the PRs listed here.

**Comment by rainphp** [comment]
I'll go through and check them now. Thanks for pointing that out Abihnav.

**Comment by webnull** [comment]
Yeah, that's very important in a community to review pull requests very often, as it's a big luck to the project that anyone want's to submit code for it.

**Comment by sitthykun** [comment]
It cannot dead on the way cos of I am using it. Not yet found any concerns.
